#!/bin/bash

# make sure wallpapers in jpg format
#
# make sure that swaybg is installed in your system
#
#
# 1. move this file to ~/.local/bin
# 2. make sure script is executable
# 3. add this line to hyprland.conf
#    exec-once = zapaper
# 4. reboat

# HAVE FUN ;)
#
wallpapers="$HOME/img" # change this the oath of your wallpapers
min=1
max=$(find "$wallpapers" -type f | wc -l)

counter=1
for file in "$wallpapers"/*; do
    # Check if it's a file (not a directory)
    if [ -f "$file" ]; then
         mv "$file" "$wallpapers/wall$counter.jpg"
        counter=$((counter + 1))
    fi
done


rundom_number=$((RANDOM % (max - min + 1) + min))
path="$wallpapers/wall$rundom_number.jpg"

swaybg -i $path -m fill
